using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Collections.Generic;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class FinesUiFragment : BoxContainer
{
    public Action<Fine>? OnAddFine;
    public Action<Fine>? OnPrintFine;

    public FinesUiFragment()
    {
        RobustXamlLoader.Load(this);

        AddButton.OnPressed += _ =>
        {
            var target = TargetInput.Text;
            var reason = ReasonInput.Text;
            var amount = (int)AmountInput.Value;

            if (string.IsNullOrWhiteSpace(target) || string.IsNullOrWhiteSpace(reason))
                return;

            OnAddFine?.Invoke(new Fine(target, reason, amount));

            // TargetInput.Text = "";
            ReasonInput.Text = "";
            AmountInput.Value = 0;
        };
    }

    public void UpdateState(List<Fine> fines)
    {
        FinesList.RemoveAllChildren();

        foreach (var fine in fines)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2)
            };

            row.AddChild(new Label { Text = $"{fine.Target}: {fine.Amount} spesos - {fine.Reason}", HorizontalExpand = true, ClipText = true });

            var printBtn = new Button { Text = "Print" };
            printBtn.OnPressed += _ => OnPrintFine?.Invoke(fine);
            row.AddChild(printBtn);

            FinesList.AddChild(row);
        }
    }
}
